languageCode = "nb-no"
title = "Fjeldborg"
baseURL = "https://fjeldborg.netlify.com/"

[params]
    pagesize = "36"

[params.posts]
    foldername = "post"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""
    disqus = ""