languageCode = "nb-no"
title = "Fjeldborg"
baseURL = "https://fjeldborg.netlify.com/"


[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""
    disqus = ""