languageCode = "nb-no"
title = "Fjeldborg"
baseURL = "http://localhost:1313/"

[params.posts]
    foldername = "post"
    pagesize = "6"
    featuredpost = "true"

[params.settings]
    googleanalytics = ""
    disqus = ""